marsctf:
    appName: marsctf
    uploadPath: /CTFFiles/  # 题目附件的存放位置
    imagePath: /CTFImages/  # 图片的存放位置
    imageUrl: /api/img/ # 图片访问的url位置
    dockerCertKeyPath: /CertKey
    log:
        path: /var/log/springboot
    token:
        header: Authorization
        secret: abcdefghijklmnopqrstuvwxyzfwagfwagwagasfwfwqrstuvwxyzfwagfwagwagasfqrstuvwxyzfwagfwagwagasf
        expireTime: 3600
    captcha:
        length: 4
        width: 100
        height: 40
        imgType: png
        expireTime: 2

server:
    port: 8080
    servlet:
        session:
            timeout: 600m
    compression:
        enabled: true
        mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://db:3306/marsdb?serverTimezone=UTC
            username: marsdb
            password: marsdb
    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 500MB
    mvc:
        static-path-pattern: /**
    web:
        resources:
            static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${marsctf.imagePath}
    redis:
        database: 1
        host: redis
        port: 6379
        password:
        connect-timeout: 60s
        timeout: 120s
        lettuce:
            pool:
                max-wait: 60s
                max-active: 20
                max-idle: 10
                min-idle: 5
