spring:
  profiles:
    active: prod

mybatis-plus:
  global-config:
    db-config:
      table-prefix: mc_
  configuration:
    map-underscore-to-camel-case: true

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true

