marsctf:
  uploadPath: /home/user01/CTFFiles/  # 题目附件的存放位置
  imagePath: /home/user01/CTFImages/  # 图片的存放位置
  imageUrl: /api/img/ # 图片访问的url位置


server:
#  port: 80
  port: 30345
#  servlet:
#    session:
#      cookie:
#        secure: true # 为了samesite：none 只对https使用cookie（仅localhost可以用http）
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/marsdb?serverTimezone=UTC
      username: root
      password: 123456
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${marsctf.imagePath}

mybatis-plus:
  global-config:
    db-config:
      table-prefix: mc_
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true




